# As per https://packaging.python.org/en/latest/tutorials/packaging-projects/
[build-system]
requires = ["setuptools>=80.0"]
build-backend = "setuptools.build_meta"

[project]
name = "streamlit-ketcher-editor"
version = "0.1.0"
authors = [
    { name="Christoph Hillisch" },
    { name="Kamil Bregula", email="dzakus13+pypi@gmail.com" },
]
description = "Ketcher editor component for Streamlit."
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE", "NOTICES"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Chemistry"
]

dependencies = [
    "streamlit>=1.64.0",
]
requires-python = ">=3.14"

[tool.setuptools]
packages = {find={}}

[tool.setuptools.package-data]
streamlit_ketcher_editor = ["py.typed"]

[tool.mypy]
files = ["streamlit_ketcher_editor"]
strict = true

[project.urls]
"Homepage" = "https://github.com/christophhillisch/streamlit-ketcher"
"Bug Tracker" = "https://github.com/christophhillisch/streamlit-ketcher/issues"
"Upstream" = "https://github.com/mik-laj/streamlit-ketcher"
